version: '3'
services:
  user_service:
    image: 'micro_a:1.0.0'
    # build: ./microA'
    ports:
      - 8000:8000
    command: ['python','run.py']
    volumes:
      - /home/diycam/Projects/property_management/microA/app:/home/pms
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: any
